apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system
namePrefix: static-cloud-
commonLabels:
  app: static-cloud-controller-manager

replicas:
  - name: deployment
    count: 1

configMapGenerator:
  - name: config.yaml
    files:
      - static-cloud-config.yaml

resources:
  - deployment.yaml
  - serviceAccount.yaml